version: '3.8'

services:

  postgresql_trips_service:
    container_name: postgresql_trips_service
    image: postgres:latest
    environment:
      - POSTGRES_DB=trips
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "10045:5432"
    volumes:
      - db_trips:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq_container:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: rootpassword
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"

volumes:
  db_trips:
    driver: local
  mongodb_data_container: