spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: "rootuser"
      password: "rootpass"
      authentication-database: "admin"

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html