server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:10045/trips
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

com:
  unsplash:
    url: https://api.unsplash.com/search/photos
    accessKey: h5QwkyV-I7MJpZV3NMVCU_mEjZol1AvzeyrRu1ngRr0

  andersen:
    chronology:
      notification:
        notification-queue-name: notification-queue-name
        notification-status-queue-name: notification-status-queue-name