server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:10045/trips
    username: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: 'root'
    password: 'rootpassword'

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

com:
  unsplash:
    url: https://api.unsplash.com/search/photos
    access-key: h5QwkyV-I7MJpZV3NMVCU_mEjZol1AvzeyrRu1ngRr0

  andersen:
    chronology:
      notification:
        notification-queue-name: notification-queue-name
        delete-calendar-event-queue-name: delete-calendar-event-queue-name
        notification-status-queue-name: notification-status-queue-name

      jwt:
        secret-key: my32CharacterUltraSecureAndUltraLongSecretKey
        jwt-expiration: 86400000
      auth:
        account-details-path: 'http://localhost:8080/api/chronology'

logging:
  level:
    org.springframework: DEBUG